In [1]:
import numpy as np
import pandas as pd

In [40]:
A = np.array([[0, 1, 1, 0, 0],
    [1, 0, 1, 0, 0],
    [1, 1, 0, 0, 0],
    [0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0]])

D = np.array([[2, 0, 0, 0, 0],
    [0, 2, 0, 0, 0],
    [0, 0, 2, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1]])

L = D - A

L

array([[ 2, -1, -1,  0,  0],
       [-1,  2, -1,  0,  0],
       [-1, -1,  2,  0,  0],
       [ 0,  0,  0,  1, -1],
       [ 0,  0,  0, -1,  1]])

In [36]:
eigenval, eigenvec = np.linalg.eig(L)
lambd = np.diag(eigenval)


In [37]:
print("Eigenval = ",eigenval)

Eigenval =  [ 3.0000000e+00 -4.4408921e-16  3.0000000e+00  2.0000000e+00
  0.0000000e+00]


In [38]:
print("Eigenvec = ",eigenvec)

Eigenvec =  [[ 0.81649658 -0.57735027  0.29329423  0.          0.        ]
 [-0.40824829 -0.57735027 -0.80655913  0.          0.        ]
 [-0.40824829 -0.57735027  0.5132649   0.          0.        ]
 [ 0.          0.          0.          0.70710678  0.70710678]
 [ 0.          0.          0.         -0.70710678  0.70710678]]


In [39]:
print("lambd = ",lambd)

lambd =  [[ 3.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00]
 [ 0.0000000e+00 -4.4408921e-16  0.0000000e+00  0.0000000e+00
   0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  3.0000000e+00  0.0000000e+00
   0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  2.0000000e+00
   0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00]]
