In [14]:
import numpy as np

In [15]:
x1 = np.array([[1, 2], [3, 4], [5, 6], [7,8]])
x2 = np.array([[1, 2], [2, 3], [5,6], [70, 80]])

evalue_x1, evector_x1 = np.linalg.eig(np.cov(x1))
evalue_x2, evector_x2 = np.linalg.eig(np.cov(x2))

In [16]:
print("eigenvalue for x1:", evalue_x1) 
print("eigenvalue for x2:", evalue_x2)

eigenvalue for x1: [-2.22044605e-16  2.00000000e+00  0.00000000e+00  0.00000000e+00]
eigenvalue for x2: [-7.10542736e-15  5.15000000e+01  0.00000000e+00  9.58658933e-16]


In [17]:
print("eigenvector for x1:", evector_x1)
print("eigenvector for x2:", evector_x2)

eigenvector for x1: [[-8.66025404e-01  5.00000000e-01 -3.71854204e-18 -3.71854204e-18]
 [ 2.88675135e-01  5.00000000e-01 -5.77350269e-01 -5.77350269e-01]
 [ 2.88675135e-01  5.00000000e-01  7.88675135e-01 -2.11324865e-01]
 [ 2.88675135e-01  5.00000000e-01 -2.11324865e-01  7.88675135e-01]]
eigenvector for x2: [[-0.99513379  0.09853293  0.         -0.08214331]
 [ 0.00975621  0.09853293  0.09901475 -0.69694538]
 [ 0.00975621  0.09853293 -0.99107935 -0.69694538]
 [ 0.09756214  0.98532928  0.08920646  0.14760341]]
